# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.openmatch.demoevaluator.install }}
kind: Service
apiVersion: v1
metadata:
  name: om-demoevaluator
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "openmatch.name" . }}
    {{- include "openmatch.chartmeta" (set . "indent" 4) }}
spec:
  selector:
    app: {{ template "openmatch.name" . }}
    component: demoevaluator
  ports:
  - name: grpc
    protocol: TCP
    port: {{ .Values.openmatch.demoevaluator.grpc.port }}
  - name: http
    protocol: TCP
    port: {{ .Values.openmatch.demoevaluator.http.port }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: om-demoevaluator
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "openmatch.name" . }}
    component: demoevaluator
    {{- include "openmatch.chartmeta" (set . "indent" 4) }}
spec:
  replicas: {{ .Values.openmatch.demoevaluator.replicas }}
  selector:
    matchLabels:
      app: {{ template "openmatch.name" . }}
      component: demoevaluator
      {{- include "openmatch.chartmeta" (set . "indent" 6) }}
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      annotations:
        {{- include "prometheus.annotations" (dict "port" .Values.openmatch.demoevaluator.http.port "prometheus" .Values.openmatch.telemetry.prometheus) | nindent 8 }}
      labels:
        app: {{ template "openmatch.name" . }}
        component: demoevaluator
        {{- include "openmatch.chartmeta" (set . "indent" 8) }}
    spec:
      {{- include "openmatch.spec.common" . | nindent 6 }}
      containers:
      - name: om-demoevaluator
        {{- include "openmatch.container.common" . | nindent 8 }}
        {{- include "openmatch.container.withredis" . | nindent 8 }}
        image: "{{ .Values.openmatch.image.registry }}/{{ .Values.openmatch.image.demoevaluator.name}}:{{ .Values.openmatch.image.tag }}"
        ports:
        - name: grpc
          containerPort: {{ .Values.openmatch.demoevaluator.grpc.port }}
        - name: http
          containerPort: {{ .Values.openmatch.demoevaluator.http.port }}
        {{- include "kubernetes.probe" (dict "port" .Values.openmatch.demoevaluator.http.port "isHTTPS" .Values.openmatch.tls.enabled) | nindent 8 }}
{{- end }}
